apm-server:
  host: "0.0.0.0:8200"
  kibana:
    enabled: true
    host: "http://kibana:5601"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
